Upgrade bedrock-quasar to v1.
digitalbazaar/bedrock-vue-organization-form pull request #3
Opened 2019-03-13 23:48 UTC by aljones15

- Remove q-field from q-input
- Add eslint-config-digitalbazaar to project
- Initial eslint setup.

Tests:
1. touch the legal name input then blur (should be invalid now and show red)
2. should be able to select an entityType

Docs:
https://v1.quasar-framework.org/

2019-03-14 00:03 UTC, aljones15 commented
p.s. the karma test from the test dir is broken. checked and this also appears to be the case in master.

2019-03-14 18:00 UTC, gannan08 commented
I think we should remove the use of filtering, other than that everything LGTM. Don't like the ergonomics of the filter and autocomplete feature.

2019-03-14 18:01 UTC, gannan08 requested changes
Remove the use of filtering/autocomplete until we find a generalized pattern that has a good user experience.

2019-03-15 14:20 UTC, gannan08 requested changes

2019-03-15 14:20 UTC, gannan08 commented on BrOrganizationForm.vue
> +      previousEntityType: null
This value is unused. Delete from data.

2019-03-15 16:40 UTC, aljones15 commented
@gannan08 also I can not get the q-select @blur and @keyup methods to fire while keyup is not surprising I would think that @blur would still work. Looking into this.

2019-03-22 18:43 UTC, gannan08 commented on entityTypes.js
> +  {
Why was this added?

2019-03-22 18:44 UTC, gannan08 requested changes
This needs to be rebased on the head of `update-company-types`.

2019-03-22 22:00 UTC, aljones15 commented
@gannan08 closing this I pushed a rebased branch with the quasar upgrade rebased from update-company types.

2019-03-22 22:00 UTC, closed without merging